test = {   'name': 'q1_4',
    'points': None,
    'suites': [   {   'cases': [   {'code': ">>> type(one_bootstrap_rr()) in set([float, np.float64]) # Make sure you're returning the relative risk!\nTrue", 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 < min(bootstrap_rrs) <= max(bootstrap_rrs) < 1\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> np.random.seed(23)\n>>> np.isclose(round(one_bootstrap_rr(), 3), 0.631)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(bootstrap_rrs) == 15\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
